behaviors:
  SnowballTarget:
    trainer_type: ppo
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    max_steps: 820000
    time_horizon: 128
    threaded: true
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: linear
      batch_size: 128
      buffer_size: 2048
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0